// SPDX-License-Identifier: MIT
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const out = (p, name) =>
  JSON.parse(readFileSync(resolve(root, `contracts/out/${p}/${name}.json`), "utf8")).abi;

const entries = {
  factoryAbi: out("UniswapV2Factory.sol", "UniswapV2Factory"),
  pairAbi: out("UniswapV2Pair.sol", "UniswapV2Pair"),
  routerAbi: out("UniswapV2Router02.sol", "UniswapV2Router02"),
  wethAbi: out("WETH9.sol", "WETH9"),
};
const banner = "// AUTO-GENERATED by scripts/sync-abis.mjs — do not edit.\n";
const body = Object.entries(entries)
  .map(([k, v]) => `export const ${k} = ${JSON.stringify(v)} as const;`)
  .join("\n");
writeFileSync(resolve(root, "packages/sdk/src/abis.ts"), banner + body + "\n");
console.log("abis.ts written");
